version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: registrationdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - registration-net

  app:
    build: .
    container_name: registration-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: registrationdb
      DB_USER: user
      DB_PASSWORD: userpassword
    networks:
      - registration-net

networks:
  registration-net:
    driver: bridge

volumes:
  mysql-data:
