apiVersion: v1
kind: Service
metadata:
  name: registration-app-service
spec:
  selector:
    app: registration-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
